### ISSUE TITLE
Missing Table - Where Did It Go?

### ISSUE THREAD

**Issue by ifdinc** [sg-p4x347/Efficient-Automatic-Traveler-System#30]
MG2237-82 - system generated a traveler for 12 to cover SO 5039507.  11 were keyed as produced on 7/13/2017.  According to Nate, nothing is in the queue for the 12th table.  

Traveler 102828.  
What happened to the 12th table?  I'm told nothing is showing to produce it, yet we only completed 11 of the 12 that were needed.

**Comment by sg-p4x347** [comment]
The traveler is not 102828, it is actually 93550.

11 items are showing as waiting to be packed
1 scrap
1 virtual item due to a bug that has since been fixed

The virtual item would have given heian2 no more parts to work on; I beieve this traveler was run on a second pack station and was therefore closed out manually
